### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by Fusselwurm** [Krzmbrzl/SQF-EclipsePlugin#1]
vllt sollte in die readme noch ein hinweis auf erforderliche plugins. dies sind fehlermeldungen die ich hatte beim installieren:

```
  Missing requirement: raven.sqf 1.0.0.201506042135 (raven.sqf 1.0.0.201506042135) requires 'bundle org.eclipse.xtext [2.8.0,3.0.0)' but it could not be found
```

**Comment by Krzmbrzl** [comment]
Kam bei der Installation kein Hinweis darauf mit der Möglichkeit diese zu installieren?

**Comment by Fusselwurm** [comment]
nee. keine ahnung warum. hatte aber zugegeben das gefühl dass eclipse auf dem ubuntu vorhin nich recht klarkam. werds nochmal aufm windows probieren :)

**Comment by Krzmbrzl** [comment]
Nee brauchste net... Hab vorher nochmal ne neue Ellipse Version installiert und hab das gleiche Problem. Ich hab die Vermutung dass ich auf meinem Testsystem doch noch n paar Sachen installiert hatte. 
Ich werde da morgen mal dran tüfteln... Sollte aber net allzu schwierig sein des hin zu bekommen

**Comment by Krzmbrzl** [comment]
Okay ich habe ne neue Installationsanleitung geschrieben, in der ich eine andere eclipse-version verlinkt habe mit der man das plugin direkt installieren kann verlinkt habe und noch eine kleine Anleitung hinzugefügt habe, um die dependencies zu installieren. <br>
[Installation](https://github.com/Krzmbrzl/SQF-EclipsePlugin/wiki/Installation) <br>
Gib mir bitte nochmal Bescheid, ob es so funktioniert. <br>
<br>

**Comment by Fusselwurm** [comment]
(Sry bin noch nicht wieder dazu gekommen, ich nehm's mir für diese Woche vor raufzugucken :) )

**Comment by Fusselwurm** [comment]
auf  Windows tut's grad :)

**Comment by Krzmbrzl** [comment]
Sehr gut danke :)
